* removed zcov, reset cover script

diff --git a/yasmina/tests/cover.sh.in b/yasmina/tests/cover.sh.in
--- a/yasmina/tests/cover.sh.in
+++ b/yasmina/tests/cover.sh.in
@@ -11,61 +11,36 @@
 #  - otherwise, the given executable is called without LCOV
 #############################################################################
 
-
 # evaluate COVER variable
-case $COVER in
-  "ZCOV")
-    # ZCOV should always be quiet
-    ZCOV="@abs_builddir@/zcov/zcov-scan"
+if test "$COVER" != "TRUE"; then
+	$*
+	exit $?
+fi
 
-    # derive test name from current directory (assuming GNU Autotest); the
-    # info filename is suffixed with a random number to allow for multiple
-    # invokations of this script for the same test
-    dir=`pwd`
-    TESTNAME=`basename $dir`
+#############################################################################
 
-    # execute executable and remember exit code
-    $*
-    result=$?
+# LCOV should always be quiet
+LCOV="@abs_builddir@/lcov/lcov --quiet"
 
-    # scan directory
-    $ZCOV @abs_builddir@/cover/$TESTNAME.zcov @abs_top_builddir@ &> /dev/null
+# derive test name from current directory (assuming GNU Autotest); the
+# info filename is suffixed with a random number to allow for multiple
+# invokations of this script for the same test
+dir=`pwd`
+TESTNAME=`basename $dir`
+INFOFILE=@abs_builddir@/cover/$TESTNAME-$RANDOM.info
 
-    # exit with executable's exit code
-    exit $result  
-  ;;
+# reset counters for LCOV
+$LCOV --zerocounters -directory @abs_top_builddir@
 
-  "LCOV")
-    # LCOV should always be quiet
-    LCOV="@abs_builddir@/lcov/lcov --quiet"
+# execute executable and remember exit code
+$*
+result=$?
 
-    # derive test name from current directory (assuming GNU Autotest); the
-    # info filename is suffixed with a random number to allow for multiple
-    # invokations of this script for the same test
-    dir=`pwd`
-    TESTNAME=`basename $dir`
-    INFOFILE=@abs_builddir@/cover/$TESTNAME-$RANDOM.info
+# evaluate coverage result of LCOV
+$LCOV --capture --directory @abs_top_builddir@ --output-file $INFOFILE --test-name $TESTNAME
 
-    # reset counters for LCOV
-    $LCOV --zerocounters -directory @abs_top_builddir@
+# remove profile information on C++ sources and headers
+$LCOV --extract $INFOFILE "@abs_top_builddir@/*" -o $INFOFILE
 
-    # execute executable and remember exit code
-    $*
-    result=$?
-
-    # evaluate coverage result of LCOV
-    $LCOV --capture --directory @abs_top_builddir@ --output-file $INFOFILE --test-name $TESTNAME
-
-    # remove profile information on C++ sources and headers
-    $LCOV --extract $INFOFILE "@abs_top_builddir@/*" -o $INFOFILE
-
-    # exit with executable's exit code
-    exit $result  
-  ;;
-
-  *)
-    $*
-    exit $?
-  ;;
-esac
-
+# exit with executable's exit code
+exit $result
