* updated PNAPI and ST-macros

diff --git a/meta/hello/tests/cover.sh.in b/meta/hello/tests/cover.sh.in
--- a/meta/hello/tests/cover.sh.in
+++ b/meta/hello/tests/cover.sh.in
@@ -1,46 +1,48 @@
 #!/bin/sh
 # @configure_input@
 
-#############################################################################
-# This script has two modes:
-#
-#  - if the environment variable COVER is set to TRUE, LCOV from the Linux
+#============================================================================#
+# AUTOTEST WRAPPER SCRIPT FOR MAIN BINARY                                    #
+# written by Niels Lohmann <niels.lohmann@uni-rostock.de>                    #
+#============================================================================#
+
+# This script has three modes:
+# 1. if the environment variable COVER is set to LCOV, LCOV from the Linux
 #    Test project (http://ltp.sourceforge.net/coverage/lcov.php) is used to
 #    collect test case coverage results for the given executable
 #
-#  - otherwise, the given executable is called without LCOV
-#############################################################################
+# 2. otherwise, the given executable is called without code coverage tool
+
 
 # evaluate COVER variable
-if test "$COVER" != "TRUE"; then
-	eval $*
-	exit $?
-fi
+case $COVER in
+  "LCOV")
+    # derive test name from current directory (assuming GNU Autotest); the
+    # info filename is suffixed with a random number to allow for multiple
+    # invokations of this script for the same test
+    dir=`pwd`
+    TESTNAME=`basename $dir`
+    INFOFILE=@abs_builddir@/cover/$TESTNAME-$RANDOM.info
 
-#############################################################################
+    # reset counters for LCOV
+    @LCOV@ --quiet --zerocounters -directory @abs_top_builddir@
 
-# LCOV should always be quiet
-LCOV="@abs_builddir@/lcov/lcov --quiet"
+    # execute executable and remember exit code
+    $*
+    result=$?
 
-# derive test name from current directory (assuming GNU Autotest); the
-# info filename is suffixed with a random number to allow for multiple
-# invokations of this script for the same test
-dir=`pwd`
-TESTNAME=`basename $dir`
-INFOFILE=@abs_builddir@/cover/$TESTNAME-$RANDOM.info
+    # evaluate coverage result of LCOV
+    @LCOV@ --quiet --capture --directory @abs_top_builddir@ --output-file $INFOFILE --derive-func-data -test-name $TESTNAME >/dev/null 2>&1
 
-# reset counters for LCOV
-$LCOV --zerocounters -directory @abs_top_builddir@
+    # remove profile information on C++ sources and headers
+    @LCOV@ --quiet --extract $INFOFILE "@abs_top_builddir@/*" -o $INFOFILE
 
-# execute executable and remember exit code
-eval $*
-result=$?
+    # exit with executable's exit code
+    exit $result  
+  ;;
 
-# evaluate coverage result of LCOV
-$LCOV --capture --directory @abs_top_builddir@ --output-file $INFOFILE --test-name $TESTNAME
-
-# remove profile information on C++ sources and headers
-$LCOV --extract $INFOFILE "@abs_top_builddir@/*" -o $INFOFILE
-
-# exit with executable's exit code
-exit $result
+  *)
+    $*
+    exit $?
+  ;;
+esac
