* documented Autoconf macros and the files in the tests folder

diff --git a/wendy/tests/cover.sh.in b/wendy/tests/cover.sh.in
--- a/wendy/tests/cover.sh.in
+++ b/wendy/tests/cover.sh.in
@@ -1,40 +1,25 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # @configure_input@
 
-#############################################################################
-# This script has two modes:
-#
-#  - if the environment variable COVER is set to TRUE, LCOV from the Linux
+#============================================================================#
+# AUTOTEST WRAPPER SCRIPT FOR MAIN BINARY                                    #
+# written by Niels Lohmann <niels.lohmann@uni-rostock.de>                    #
+#============================================================================#
+
+# This script has three modes:
+# 1. if the environment variable COVER is set to LCOV, LCOV from the Linux
 #    Test project (http://ltp.sourceforge.net/coverage/lcov.php) is used to
 #    collect test case coverage results for the given executable
 #
-#  - otherwise, the given executable is called without LCOV
-#############################################################################
+# 2. if the environment variable COVER is set to ZCOV, zcov is used to
+#    collect test case coverage results for the given executable; see
+#    http://minormatter.com/zcov/ for more information
+#
+# 3. otherwise, the given executable is called without code coverage tool
 
 
 # evaluate COVER variable
 case $COVER in
-  "ZCOV")
-    # ZCOV should always be quiet
-    ZCOV="@abs_builddir@/zcov/zcov-scan"
-
-    # derive test name from current directory (assuming GNU Autotest); the
-    # info filename is suffixed with a random number to allow for multiple
-    # invokations of this script for the same test
-    dir=`pwd`
-    TESTNAME=`basename $dir`
-
-    # execute executable and remember exit code
-    $*
-    result=$?
-
-    # scan directory
-    $ZCOV @abs_builddir@/cover/$TESTNAME.zcov @abs_top_builddir@ &> /dev/null
-
-    # exit with executable's exit code
-    exit $result  
-  ;;
-
   "LCOV")
     # LCOV should always be quiet
     LCOV="@abs_builddir@/lcov/lcov --quiet"
@@ -63,9 +48,29 @@ case $COVER in
     exit $result  
   ;;
 
+  "ZCOV")
+    # set ZCOV variable
+    ZCOV="@abs_builddir@/zcov/zcov-scan"
+
+    # derive test name from current directory (assuming GNU Autotest); the
+    # info filename is suffixed with a random number to allow for multiple
+    # invokations of this script for the same test
+    dir=`pwd`
+    TESTNAME=`basename $dir`
+
+    # execute executable and remember exit code
+    $*
+    result=$?
+
+    # scan directory
+    $ZCOV @abs_builddir@/cover/$TESTNAME.zcov @abs_top_builddir@ &> /dev/null
+
+    # exit with executable's exit code
+    exit $result  
+  ;;
+
   *)
     $*
     exit $?
   ;;
 esac
-
